// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs';

// /** @type {import('eslint').Linter.Config} */
export default withNuxt({
	ignores: ['node_modules/', 'dist/', '.nuxt/', '.output/', '.husky', '.nuxt', 'components/','pages/', 'services/', 'types/'],
	rules: {
		'capitalized-comments': ['off', 'always'],
		'default-case-last': 'off',
		'no-dupe-else-if': 'off',
		'no-dupe-keys': 'off',
		'vue/no-dupe-v-else-if': 'off',
		'no-alert': 'off',
		'no-unused-vars': 'off',
		'@typescript-eslint/no-unused-vars': 'off',
		'prefer-const': 'off',
		'@typescript-eslint/init-declarations': 'off',
		'init-declarations': 'off',
		'prefer-arrow-callback': 'off',
		'no-var': 'off',
		'vue/arrow-spacing': 'off',
		'no-duplicate-imports': 'off',
		'no-implicit-globals': 'off',
		'@typescript-eslint/no-unused-expressions': 'off',
		'vue/valid-attribute-name': 'off',
		'vue/attributes-order': 'off',
		'vue/no-multiple-template-root': 'off',
		'vue/no-v-html': 'off',
		'vue/require-v-for-key': 'off',
		'vue/attribute-hyphenation': 'off',
		'vue/no-async-in-computed-properties': 'off',
		'vue/no-template-key': 'off',
		'vue/no-unused-components': 'off',
		'vue/no-mutating-props': 'off',
		'vue/valid-template-root': 'off',
		'vue/no-side-effects-in-computed-properties': 'off',
		'no-empty-function': 'off',
		'no-useless-catch': 'off',
		'no-useless-return': 'off',
		'no-useless-escape': 'off',
		'@typescript-eslint/no-explicit-any': 'off',
		'@typescript-eslint/no-extraneous-class': 'off',
		'vue/require-explicit-emits': 'off',
	},
});
